{"uuid":"6f33b2c8-d7e3-434e-8cbb-feec537a116a","historyId":"f24a940bceaf9ddcd34c71d76c01d428","fullName":"UITests.saucedemo.LoginTest.successfulLoginTest","labels":[{"name":"package","value":"UITests.saucedemo.LoginTest"},{"name":"testClass","value":"UITests.saucedemo.LoginTest"},{"name":"testMethod","value":"successfulLoginTest"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"Ramwaste_Project"},{"name":"subSuite","value":"UITests.saucedemo.LoginTest"},{"name":"host","value":"tshalikianis-MacBook-Pro.local"},{"name":"thread","value":"89215@tshalikianis-MacBook-Pro.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Successful Login"},{"name":"epic","value":"Sauce Demo Platform Tests"},{"name":"feature","value":"Login Functionality"}],"links":[],"name":"successfulLoginTest","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"No user found with username: standard_user","trace":"java.lang.RuntimeException: No user found with username: standard_user\n\tat org.example.data.saucedemo.DatabaseManager.getPassword(DatabaseManager.java:30)\n\tat org.example.Steps.saucedemo.LoginSteps.correctLogin(LoginSteps.java:33)\n\tat UITests.saucedemo.LoginTest.successfulLoginTest(LoginTest.java:44)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:829)\n\tat org.testng.TestRunner.run(TestRunner.java:602)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:437)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:330)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1176)\n\tat org.testng.TestNG.runSuites(TestNG.java:1099)\n\tat org.testng.TestNG.run(TestNG.java:1067)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\n"},"stage":"finished","description":"Verify successful login and image loading.","steps":[],"attachments":[],"parameters":[],"start":1753399170955,"stop":1753399170956}