{"uuid":"d428990f-fc9c-41e0-b3b4-125b479cc319","historyId":"f2d4b9f6f6f3a9795b0eb09cd2c73868","fullName":"UITests.saucedemo.LoginTest.bannedUserLoginTest","labels":[{"name":"package","value":"UITests.saucedemo.LoginTest"},{"name":"testClass","value":"UITests.saucedemo.LoginTest"},{"name":"testMethod","value":"bannedUserLoginTest"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"Ramwaste_Project"},{"name":"subSuite","value":"UITests.saucedemo.LoginTest"},{"name":"host","value":"tshalikianis-MacBook-Pro.local"},{"name":"thread","value":"88095@tshalikianis-MacBook-Pro.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Banned User Login"},{"name":"epic","value":"Sauce Demo Platform Tests"},{"name":"feature","value":"Login Functionality"}],"links":[],"name":"bannedUserLoginTest","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"No user found with username: locked_out_user","trace":"java.lang.RuntimeException: No user found with username: locked_out_user\n\tat org.example.data.saucedemo.DatabaseManager.getPassword(DatabaseManager.java:28)\n\tat org.example.Steps.saucedemo.LoginSteps.inCorrectLogin(LoginSteps.java:41)\n\tat UITests.saucedemo.LoginTest.bannedUserLoginTest(LoginTest.java:50)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:829)\n\tat org.testng.TestRunner.run(TestRunner.java:602)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:437)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:330)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1176)\n\tat org.testng.TestNG.runSuites(TestNG.java:1099)\n\tat org.testng.TestNG.run(TestNG.java:1067)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\n"},"stage":"finished","description":"Verify login fails for a locked out user.","steps":[],"attachments":[],"parameters":[],"start":1753398642681,"stop":1753398642681}